apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3proxy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "s3proxy.name" . }}
    helm.sh/chart: {{ include "s3proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  JCLOUDS_PROVIDER: "azureblob"
  JCLOUDS_IDENTITY: {{ .Values.azure.accountName | quote }}
  JCLOUDS_CREDENTIAL: {{ .Values.azure.accountKey | quote }}
  JCLOUDS_ENDPOINT: "https://{{ .Values.azure.accountName }}.blob.core.windows.net"